import { mkdir, unlink, writeFile } from "node:fs/promises";
import path from "node:path";

export const AGENT_SERVICE_LABEL = "ai.allin.allinai-agent";

export type UserServiceFileSystem = {
  mkdir(dir: string, options: { recursive: true }): Promise<string | undefined>;
  writeFile(
    file: string,
    content: string,
    options: { encoding: "utf8"; mode: number },
  ): Promise<void>;
  unlink(file: string): Promise<void>;
};

export type UserServiceExecutor = (
  file: string,
  args: readonly string[],
) => Promise<void>;

export type UserServiceDefinition = {
  executable: string;
  configDir: string;
};

export type LaunchAgentActionOptions = UserServiceDefinition & {
  homeDir: string;
  uid: number;
  fileSystem?: UserServiceFileSystem;
  execute?: UserServiceExecutor;
};

const serviceFs: UserServiceFileSystem = { mkdir, writeFile, unlink };

function isSafeAbsolutePath(value: string): boolean {
  return (
    path.isAbsolute(value) &&
    value.length > 1 &&
    !value.includes("\0") &&
    !/[\r\n]/.test(value)
  );
}

function assertDefinition(input: UserServiceDefinition): void {
  if (!isSafeAbsolutePath(input.executable)) {
    throw new TypeError("Service executable must be an absolute path");
  }
  if (!isSafeAbsolutePath(input.configDir)) {
    throw new TypeError("Service configDir must be an absolute path");
  }
}

function xml(value: string): string {
  return value
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&apos;");
}

/** The only macOS service destination this package will write. */
export function launchAgentPath(homeDir: string): string {
  if (!isSafeAbsolutePath(homeDir)) {
    throw new TypeError("User homeDir must be an absolute path");
  }
  return path.join(
    homeDir,
    "Library",
    "LaunchAgents",
    `${AGENT_SERVICE_LABEL}.plist`,
  );
}

/**
 * Deterministic user-scoped launchd definition. Credentials are deliberately
 * absent: the daemon reads the local credential store after launch.
 */
export function buildLaunchAgentPlist(input: UserServiceDefinition): string {
  assertDefinition(input);
  const stdout = path.join(input.configDir, "logs", "launchd.stdout.log");
  const stderr = path.join(input.configDir, "logs", "launchd.stderr.log");
  return `<?xml version="1.0" encoding="UTF-8"?>\n<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">\n<plist version="1.0">\n<dict>\n  <key>Label</key>\n  <string>${AGENT_SERVICE_LABEL}</string>\n  <key>ProgramArguments</key>\n  <array>\n    <string>${xml(input.executable)}</string>\n    <string>daemon</string>\n    <string>--config-dir</string>\n    <string>${xml(input.configDir)}</string>\n  </array>\n  <key>RunAtLoad</key>\n  <true/>\n  <key>KeepAlive</key>\n  <true/>\n  <key>ProcessType</key>\n  <string>Background</string>\n  <key>StandardOutPath</key>\n  <string>${xml(stdout)}</string>\n  <key>StandardErrorPath</key>\n  <string>${xml(stderr)}</string>\n</dict>\n</plist>\n`;
}

function assertUserUid(uid: number): void {
  if (!Number.isSafeInteger(uid) || uid <= 0) {
    throw new Error("Agent service installation requires a non-root user");
  }
}

/** Install only a LaunchAgent owned by the invoking non-root user. */
export async function installLaunchAgent(
  options: LaunchAgentActionOptions,
): Promise<string> {
  assertDefinition(options);
  assertUserUid(options.uid);
  const destination = launchAgentPath(options.homeDir);
  const fs = options.fileSystem ?? serviceFs;
  const execute = options.execute ?? defaultLaunchctl;
  await fs.mkdir(path.dirname(destination), { recursive: true });
  await fs.mkdir(path.join(options.configDir, "logs"), { recursive: true });
  await fs.writeFile(destination, buildLaunchAgentPlist(options), {
    encoding: "utf8",
    mode: 0o644,
  });
  await execute("launchctl", ["bootstrap", `gui/${options.uid}`, destination]);
  return destination;
}

/** Stop first, then remove only the exact file generated by this package. */
export async function uninstallLaunchAgent(
  options: Omit<LaunchAgentActionOptions, "executable" | "configDir">,
): Promise<string> {
  assertUserUid(options.uid);
  const destination = launchAgentPath(options.homeDir);
  const fs = options.fileSystem ?? serviceFs;
  const execute = options.execute ?? defaultLaunchctl;
  await execute("launchctl", ["bootout", `gui/${options.uid}`, destination]);
  await fs.unlink(destination);
  return destination;
}

async function defaultLaunchctl(
  file: string,
  args: readonly string[],
): Promise<void> {
  const { execFile } = await import("node:child_process");
  await new Promise<void>((resolve, reject) => {
    execFile(file, [...args], { shell: false }, (error) => {
      if (error) reject(error);
      else resolve();
    });
  });
}
